### ISSUE TITLE
Intel MPI provider

### ISSUE THREAD

**Issue by dalcinl** [conda-forge/mpi-feedstock#11]
### Comment:

We must update this feedstock for Intel MPI.

Intel MPI in conda-forge comes as a copy from the `intel` channel. There are two packages involved, `impi_rt` with the runtime components (`mpiexec` and shared libraries) , and `impi-devel` with the development components (`mpicc` and related and headers).

Given that Intel MPI is not built from source, but rather comes from a vendor as pre-built binary packages, there are many details that make it different from other MPI providers:

1. As I already mention, the MPI provider is split in two packages. Should we create a `impi` metapackage that would explicitly depend on `impi_rt` and `impi-devel`? Is there any way to automate this process when the core packages get updated from the intel channel?
2. There is no `impi-mpicc` package. Moreover, `mpicc` does use the `$CC` compiler command from the compiler package, so conda recipes require explicitly setting `I_MPI_CC=$CC`. 

I don't know how to update the `mpi-feedstock` repository to add the new provider. Should we add `impi-rt`, or `impi-devel`, or what?  Or should we address point 1 above and have a `impi` package, making the convention simple and uniform across MPI providers?

@isuruf @ocefpaf @minrk I really need some input here.

**Comment by leofang** [comment]
@dalcinl It doesn't matter. We use this `mpi` package as a mutex. So we just need to add `intelmpi` as the mutex identifier. Then, in the intel-mpi recipe (not sure if it's already a thing, I haven't looked), we need to add `mpi 1.0 intelmpi` to `run`, like this:
https://github.com/conda-forge/openmpi-feedstock/blob/445ff315d7b321708d22a251d72daae3847d94dc/recipe/meta.yaml#L122-L123

**Comment by leofang** [comment]
We just need to update this file: https://github.com/conda-forge/mpi-feedstock/blob/main/recipe/conda_build_config.yaml

**Comment by dalcinl** [comment]
So this means that we really need to create our own `impi` package to implement conda-forge channel conventions. This package would depend explicitly of `impi_rt` and `impi-devel`. This way we have the mutex properly working. Additionally, the recipe should generate a proper `impi-mpicc` package as well fixing the compiler  command issue.

But now I have a problem: How can we automate version updates? And new `impi` package version should be produced whenever new releases of `impi_rt` and `impi-devel` package are copied over from the intel channel (via the `intel_repack-feedstock`).

**Comment by leofang** [comment]
I am probably confused: How/where would we fetch the source if we build `impi` package on conda-forge?

**Comment by dalcinl** [comment]
@leofang We DO NOT build the `impi` package. The package is "manually" copied over from the anaconda.org `intel` channel. All the magic happens in the `intel_repack-feedstock` [[link to recipe]](https://github.com/conda-forge/intel_repack-feedstock/blob/main/recipe/meta.yaml).

**Comment by dalcinl** [comment]
To create our own `impi` package, there are no real sources to fetch. We just need to create a metapackage that explicitly depends on the `impi_rt` and `impi-devel` packages. But I would really like to get version updates automated, otherwise it is yet another thing to keep track by hand.

**Comment by leofang** [comment]
Ah, isn't it a lot simpler, then? We just need to add the constraint to `impi_rt`'s `run`. (And either mark the old ones as broken, given they do not have the constraint, or patch their repodata.) The version update would be taken care of when the feedstock is updated. You can declare dependencies among multiple outputs of the same recipe.

> there are no real sources to fetch.

I didn't know these are hidden in `intel_repack-feedstock`, if we were to create a new feedstock I'd just follow what's done there: https://github.com/conda-forge/intel_repack-feedstock/blob/9b2263fb7ef0d0b83064a19635793264d1634b0d/recipe/meta.yaml#L65-L70.

**Comment by dalcinl** [comment]
I don't think creating a new feedstock is the bert option. I would first try to get the @conda-forge/intel_repack team on board. They already manifested their interest in keeping things clean and lean, without adding extra stuff beyond what is extrictly needed for the repack operations. However, Intel MPI is a bit special, as it is supposed to interplay with other MPI providers, so maybe we can make them add an exception and create an additional `impi` metapackage (and maybe `impi-mpi{cc|cxx|fort}` ?).

Otherwise, how can we manage a `impi` metapackage separately, getting the bot to trigger updates every time `intel_repack` issues an updated Intel MPI version? 

@conda-forge-admin, please ping @conda-forge/intel_repack

**Comment by leofang** [comment]
I don't think we need a new `impi` package. Since `impi-devel` depends on `impi_rt`, it'd get the dependency on the `mpi` mutex indirectly, thus we really just need a one-liner change to `impi_rt` as I suggested earlier. Let's not overcomplicate it :)

**Comment by leofang** [comment]
@oleksandr-pavlyk WDYT?

**Comment by leofang** [comment]
@dalcinl Is your concern mainly about mpicc etc?

**Comment by dalcinl** [comment]
Mi main concern is that the the Intel MPI package in conda-forge does not follow the packaging rules of the other MPI providers. With have two packages with `_rt` and `-devel` suffixes, and (less important) we do not have `impi-mpicc/cxx/fort `packages, making the thing more complicated to use in in build/deployment scripts, recipes, CI, etc., not to mention that so far conda-forge do not usually distinguish between runtime and development packages, you `conda install foo` and you get the whole foo.  That's the reason I'm advocating for a new `impi` metapackage that would bing in the whole thing. If we already had it, the `mpi-feedstock` would just need a single line `impi` to add the new provider, `conda install impi` would give us the whole thing allowing to run and compile code.

**Comment by leofang** [comment]
I get that you want mpicc etc and I think we should just add additional outputs to intel_repack-feedstock. But
> If we already had it, the `mpi-feedstock` would just need a single line `impi` to add the new provider

This sounds odd to me. I feel you're mixing up `conda install impi` (which I agree is nice to have) with `conda install mpi` (no one does this, the `mpi` mutex is empty, it's used as a constraint). 

With my suggestion above, I can assure you either this
```
conda install impi-devel
```
or this
```
conda install impi_rt
```
will work properly (creating conflicts when users attempt to follow with say `conda install openmpi`). Other things (metapackage `impi` or compiler wrapper `impi-mpicc` etc) are for better UX (for users or CF package maintainers) and they should be generated from intel_repack-feedstock too.

**Comment by dalcinl** [comment]
> I feel you're mixing up `conda install impi`

I truly meant `conda install impi`, that is the Intel MPI metapackage that would explicitly bring in the runtime `impi_rt` and development `impi-devel` package.  Never mind, perhaps I mistyped somewhere. This makes me wondering wheter we should prefer "intelmpi" as a name.

> With my suggestion above, I can assure you either this
> ...
> Other things ... are for better UX

Oh, now I see what you meant. You are splitting my concerns in two orthogonal aspects:

1. Setting up the mutex properly. IIUC, that requires adding `impi_rt` as a provider in the `mpi-feedstock` recipe. This can be done with very minor (and likely unobjectionable) modifications to the `intel_repack` feedstock.
2. Improve the UX . This implies adding a `impi` (or `intelmpi`? ) metapackage (with deps on _rt and -devel) to ensure (now and in the future if Intel upstream changes conventions) to get the whole Of Intel MPI installed in one shot. Also add `impi-mpi{cc|cxx|fort}` if possible. This would require some more substantial additions to the  `intel_repack` recipe, and we may get (understandable) resistance from the maintainers. Perhaps there is a way to do it without loading the mess on `intel_repack`'shoulders.

**Comment by leofang** [comment]
Yes. To recap my suggestions above:
- [x] Add `intelmpi` (or `impi`, I honestly don't care) as a mutex identifier to this (`mpi`) feedstock
- [x] Add `- run: mpi 1.0 intelmpi` to `impi_rt` in intel_repack-feedstock
- [ ] Add `impi`, `impi-mpicc` & co in intel_repack-feedstock
- [x] Add `run_exports` to `impi-devel` in intel_repack-feedstock
- [x] Patch the repodata of old `impi_rt` & `impi-devel` that were not constrained by `mpi`

I think for consuming Intel MPI in the conda-forge CI, the 3rd step (which was what you asked for) is necessary. @conda-forge/intel_repack @conda-forge/core any objection before someone (Lisandro?) starts the work?

**Comment by napetrov** [comment]
1st and 2nd - are good to go i think. 

In terms of naming on 3rd I've shared to impi team.

**Comment by leofang** [comment]
(Update: Added a 4th step to the TODO list above to capture an earlier comment.)

**Comment by beckermr** [comment]
@leofang @dalcinl @conda-forge/core I am seeing conda install both impi_rt and openmpi in the same environment:

```
Looking for: ['numpy', 'numba', 'emcee', 'scipy', 'tqdm', 'pyyaml', 'jax', 'mpi4py', 'openmpi', 'corrfunc', "halotools[version='>=0.7']", "astropy[version='>=4']", 'fast3tree', 'h5py', 'mpipartition', 'psutil', 'python=3.9']
  
  
  Transaction
  
    Prefix: /usr/share/miniconda3/envs/test
  
    Updating specs:
  
     - numpy
     - numba
     - emcee
     - scipy
     - tqdm
     - pyyaml
     - jax
     - mpi4py
     - openmpi
     - corrfunc
     - halotools[version='>=0.7']
     - astropy[version='>=4']
     - fast3tree
     - h5py
     - mpipartition
     - psutil
     - python=3.9
  
  
    Package                    Version  Build                   Channel                   Size
  ──────────────────────────────────────────────────────────────────────────────────────────────
    Install:
  ──────────────────────────────────────────────────────────────────────────────────────────────
  
    + _libgcc_mutex                0.1  conda_forge             conda-forge/linux-64       3kB
    + _openmp_mutex                4.5  2_gnu                   conda-forge/linux-64      24kB
    + astropy                    5.3.4  py39h44dd56e_2          conda-forge/linux-64       8MB
    + beautifulsoup4            4.12.2  pyha770c72_0            conda-forge/noarch       115kB
    + brotli-python              1.1.0  py39h3d6467e_1          conda-forge/linux-64     350kB
    + bzip2                      1.0.8  h7f98852_4              conda-forge/linux-64     496kB
    + c-ares                    1.20.1  hd590300_1              conda-forge/linux-64     116kB
    + ca-certificates        2023.7.22  hbcca054_0              conda-forge/linux-64     150kB
    + cached-property            1.5.2  hd8ed1ab_1              conda-forge/noarch         4kB
    + cached_property            1.5.2  pyha770c72_1            conda-forge/noarch        11kB
    + certifi                2023.7.22  pyhd8ed1ab_0            conda-forge/noarch       154kB
    + charset-normalizer         3.3.1  pyhd8ed1ab_0            conda-forge/noarch        47kB
    + colorama                   0.4.6  pyhd8ed1ab_0            conda-forge/noarch        25kB
    + corrfunc                   2.5.2  py39h42e8f01_0          conda-forge/linux-64      86MB
    + emcee                      3.1.4  pyhd8ed1ab_0            conda-forge/noarch        38kB
    + fast3tree                  0.4.1  py39h44dd56e_2          conda-forge/linux-64      97kB
    + future                    0.18.3  pyhd8ed1ab_0            conda-forge/noarch       366kB
    + gsl                          2.7  he838d99_0              conda-forge/linux-64       3MB
    + h5py                      3.10.0  nompi_py39h87cadad_100  conda-forge/linux-64       1MB
    + halotools                  0.8.2  py39hddac248_1          conda-forge/linux-64       2MB
    + hdf5                      1.14.2  nompi_h4f84152_100      conda-forge/linux-64       4MB
    + idna                         3.4  pyhd8ed1ab_0            conda-forge/noarch        57kB
    + impi_rt                2021.10.0  ha770c72_50371          conda-forge/linux-64      25MB
    + importlib-metadata         6.8.0  pyha770c72_0            conda-forge/noarch        26kB
    + importlib_metadata         6.8.0  hd8ed1ab_0              conda-forge/noarch         9kB
    + jax                       0.4.17  pyhd8ed1ab_0            conda-forge/noarch         1MB
    + jaxlib                    0.4.14  cpu_py39h45b9b01_1      conda-forge/linux-64      48MB
    + keyutils                   1.6.1  h166bdaf_0              conda-forge/linux-64     118kB
    + krb5                      1.21.2  h659d440_0              conda-forge/linux-64       1MB
    + ld_impl_linux-64            2.40  h41732ed_0              conda-forge/linux-64     705kB
    + libabseil             20230802.1  cxx17_h59595ed_0        conda-forge/linux-64       1MB
    + libaec                     1.1.2  h59595ed_1              conda-forge/linux-64      35kB
    + libblas                    3.9.0  19_linux64_openblas     conda-forge/linux-64      15kB
    + libcblas                   3.9.0  19_linux64_openblas     conda-forge/linux-64      14kB
    + libcurl                    8.4.0  hca28451_0              conda-forge/linux-64     386kB
    + libedit             3.1.20191231  he28a2e2_2              conda-forge/linux-64     124kB
    + libev                       4.33  h516909a_1              conda-forge/linux-64     106kB
    + libffi                     3.4.2  h7f98852_5              conda-forge/linux-64      58kB
    + libgcc-ng                 13.2.0  h807b86a_2              conda-forge/linux-64     771kB
    + libgfortran-ng            13.2.0  h69a702a_2              conda-forge/linux-64      24kB
    + libgfortran5              13.2.0  ha4646dd_2              conda-forge/linux-64       1MB
    + libgomp                   13.2.0  h807b86a_2              conda-forge/linux-64     421kB
    + libgrpc                   1.58.1  he06187c_2              conda-forge/linux-64       7MB
    + liblapack                  3.9.0  19_linux64_openblas     conda-forge/linux-64      14kB
    + libllvm14                 14.0.6  hcd5def8_4              conda-forge/linux-64      31MB
    + libnghttp2                1.52.0  h61bc06f_0              conda-forge/linux-64     622kB
    + libnsl                     2.0.1  hd590300_0              conda-forge/linux-64      33kB
    + libopenblas               0.3.24  pthreads_h413a1c8_0     conda-forge/linux-64       5MB
    + libprotobuf               4.24.3  hf27288f_1              conda-forge/linux-64       3MB
    + libre2-11             2023.06.02  h7a70373_0              conda-forge/linux-64     233kB
    + libsqlite                 3.43.2  h2797004_0              conda-forge/linux-64     840kB
    + libssh2                   1.11.0  h0841786_0              conda-forge/linux-64     271kB
    + libstdcxx-ng              13.2.0  h7e041cc_2              conda-forge/linux-64       4MB
    + libuuid                   2.38.1  h0b41bf4_0              conda-forge/linux-64      34kB
    + libzlib                   1.2.13  hd590300_5              conda-forge/linux-64      62kB
    + llvmlite                  0.40.1  py39h174d805_0          conda-forge/linux-64       3MB
    + ml_dtypes                  0.3.1  py39hddac248_2          conda-forge/linux-64     160kB
    + mpi                          1.0  openmpi                 conda-forge/linux-64       4kB
    + mpi4py                     3.1.5  py39h03e9507_0          conda-forge/linux-64     544kB
    + mpipartition               1.1.3  pyhd8ed1ab_0            conda-forge/noarch        23kB
    + ncurses                      6.4  hcb278e6_0              conda-forge/linux-64     881kB
    + numba                     0.57.1  py39hb75a051_0          conda-forge/linux-64       4MB
    + numpy                     1.24.4  py39h6183b62_0          conda-forge/linux-64       7MB
    + openmpi                    4.1.6  hc5af2df_101            conda-forge/linux-64       4MB
    + openssl                    3.1.3  hd590300_0              conda-forge/linux-64       3MB
    + opt-einsum                 3.3.0  hd8ed1ab_2              conda-forge/noarch         7kB
    + opt_einsum                 3.3.0  pyhc1e730c_2            conda-forge/noarch        58kB
    + packaging                   23.2  pyhd8ed1ab_0            conda-forge/noarch        49kB
    + pip                       23.3.1  pyhd8ed1ab_0            conda-forge/noarch         1MB
    + psutil                     5.9.5  py39hd1e30aa_1          conda-forge/linux-64     359kB
    + pyerfa                   2.0.1.1  py39h44dd56e_0          conda-forge/linux-64     356kB
    + pysocks                    1.7.1  pyha2e5f31_6            conda-forge/noarch        19kB
    + python                    3.9.18  h0755[675](https://github.com/ArgonneCPAC/diffsmhm/actions/runs/6616324850/job/17970351052#step:4:686)_0_cpython      conda-forge/linux-64      24MB
    + python_abi                   3.9  4_cp39                  conda-forge/linux-64       6kB
    + pyyaml                     6.0.1  py39hd1e30aa_1          conda-forge/linux-64     178kB
    + re2                   2023.06.02  h2873b5e_0              conda-forge/linux-64      27kB
    + readline                     8.2  h8228510_1              conda-forge/linux-64     281kB
    + requests                  2.31.0  pyhd8ed1ab_0            conda-forge/noarch        57kB
    + scipy                     1.11.3  py39h474f0d3_1          conda-forge/linux-64      15MB
    + setuptools                68.2.2  pyhd8ed1ab_0            conda-forge/noarch       464kB
    + soupsieve                    2.5  pyhd8ed1ab_1            conda-forge/noarch        37kB
    + tk                        8.6.13  h2797004_0              conda-forge/linux-64       3MB
    + tqdm                      4.66.1  pyhd8ed1ab_0            conda-forge/noarch        89kB
    + tzdata                     2023c  h71feb2d_0              conda-forge/noarch       118kB
    + urllib3                    2.0.7  pyhd8ed1ab_0            conda-forge/noarch        99kB
    + wheel                     0.41.2  pyhd8ed1ab_0            conda-forge/noarch        57kB
    + wurlitzer                  3.0.3  pyhd8ed1ab_0            conda-forge/noarch        12kB
    + xz                         5.2.6  h166bdaf_0              conda-forge/linux-64     418kB
    + yaml                       0.2.5  h7f98852_2              conda-forge/linux-64      89kB
    + zipp                      3.17.0  pyhd8ed1ab_0            conda-forge/noarch        19kB
    + zlib                      1.2.13  hd590300_5              conda-forge/linux-64      93kB
    + zstd                       1.5.5  hfc55251_0              conda-forge/linux-64     545kB
 ```

Something is not pinned correctly.

**Comment by beckermr** [comment]
I think we need a repodata patch?

**Comment by leofang** [comment]
Things go wrong because 
1. the mutex is not set up yet
2. `impi-rt` does not set `run_exports` like `openmpi`/`mpich` do (see [discussions here](https://github.com/conda-forge/mpi4py-feedstock/pull/66))
3. `mpi4py` prematurely built against `impi` (https://github.com/conda-forge/mpi4py-feedstock/pull/65)

We'll need to rectify by doing [the steps I outlined above](https://github.com/conda-forge/mpi-feedstock/issues/11#issuecomment-1769101283). But I really don't have time today (maybe tomorrow too).

**Comment by leofang** [comment]
(Update: Add a step to the checklist regarding `run_exports`.)

**Comment by beckermr** [comment]
OK. We cannot break envs like this, so we need to mark the offending packages/versions as broken and can readd them when things are up to date.

**Comment by beckermr** [comment]
Which packages are causing the issue? Is it just the impi builds of mpi4py or others as well?

**Comment by leofang** [comment]
I agree, but unfortunately I don't even have time to submit an admin request; replying questions is already taking my spare time today. All `impi_rt`/`impi-devel`/`mpi4py` need to be marked as broken.

**Comment by beckermr** [comment]
I am happy to make the PR. I simply need to know which packages are effected. The list above is enough. Thank you!

**Comment by dalcinl** [comment]
> I simply need to know which packages are effected.

Please note that only mpi4py+impi packages are broken, the others (mpi4py+mpich/openmpi/msmpi) are OK. Not sure if they can be easily filtered, though.

**Comment by beckermr** [comment]
kk let me look - hopefully the build strings have the info we need

**Comment by beckermr** [comment]
@leofang This one should address at least one of the items above: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/579

**Comment by leofang** [comment]
See https://github.com/conda-forge/intel_repack-feedstock/pull/57 for Steps 2 & 4 above.

**Comment by leofang** [comment]
Thank to all. All steps on the checklist are done except for Step 3, which is not critical and is tracked here: https://github.com/conda-forge/intel_repack-feedstock/issues/58. Let's close this issue.
