### ISSUE TITLE
Linker fails with new compilers on mac

### ISSUE THREAD

**Issue by mikaem** [conda-forge/mpi-feedstock#4]
Issue:
I'm reporting here because problem if found with both openmpi and mpich.

The following works on linux, but fails on mac. Using [helloworld.c](https://github.com/conda-forge/mpich-feedstock/blob/master/recipe/tests/helloworld.c)

    conda create --name mpich mpich mpich-mpicc
    conda activate mpich
    mpicc helloworld.c -o helloworld_c

fails with:

    ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, file was built for unsupported file format ( 0x2D 0x2D 0x2D 0x20 0x21 0x74 0x61 0x70 0x69 0x2D 0x74 0x62 0x64 0x2D 0x76 0x33 ) which is not the architecture being linked (x86_64): /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
    ld: in '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.B.tbd', file was built for unsupported file format ( 0x2D 0x2D 0x2D 0x20 0x21 0x74 0x61 0x70 0x69 0x2D 0x74 0x62 0x64 0x2D 0x760x33 ) which is not the architecture being linked (x86_64): /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.B.tbd for architecture x86_64
    clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)

Similarly with openmpi

    conda create --name openmpi openmpi openmpi-mpicc
    conda activate openmpi
    mpicc helloworld.c -o helloworld_c

fails with

    ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, file was built for unsupported file format ( 0x2D 0x2D 0x2D 0x20 0x21 0x74 0x61 0x70 0x69 0x2D 0x74 0x62 0x64 0x2D 0x76 0x33 ) which is not the architecture being linked (x86_64): /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
    Undefined symbols for architecture x86_64:
      "___stack_chk_fail", referenced from:
          _main in helloworld-f222ad.o
      "___stack_chk_guard", referenced from:
          _main in helloworld-f222ad.o
      "_printf", referenced from:
          _main in helloworld-f222ad.o
    ld: symbol(s) not found for architecture x86_64
    clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)

Probably has to do with me using MacOSX10.14.sdk, but I'm not sure how to overcome it (ping @minrk)? 

<br/>
Environment (<code>conda list</code>):

<details>

```
With mpich:

# packages in environment at /Users/mikaelmortensen/anaconda3/envs/mpi:
#
# Name                    Version                   Build  Channel
cctools                   895                  h7512d6f_0    conda-forge
clang                     4.0.1                h662ec87_0    conda-forge
clang_osx-64              4.0.1               h1ce6c1d_11    conda-forge
compiler-rt               4.0.1                h5487866_0    conda-forge
ld64                      274.2                h7c2db76_0    conda-forge
libcxx                    4.0.1                h579ed51_0    defaults
libcxxabi                 4.0.1                hebd6815_0    conda-forge
libgfortran               3.0.1                h93005f0_2    defaults
llvm                      4.0.1                hc748206_0    conda-forge
llvm-lto-tapi             4.0.1                h6701bc3_0    conda-forge
mpi                       1.0                       mpich    conda-forge
mpich                     3.2.1             h71abe9c_1008    conda-forge
mpich-mpicc               3.2.1             h79c3c89_1008    conda-forge

With openmpi:

# packages in environment at /Users/mikaelmortensen/anaconda3/envs/openmpi:
#
# Name                    Version                   Build  Channel
cctools                   895                  h7512d6f_0    conda-forge
clang                     4.0.1                h662ec87_0    conda-forge
clang_osx-64              4.0.1               h1ce6c1d_11    conda-forge
compiler-rt               4.0.1                h5487866_0    conda-forge
ld64                      274.2                h7c2db76_0    conda-forge
libcxx                    4.0.1                h579ed51_0    defaults
libcxxabi                 4.0.1                hebd6815_0    conda-forge
libgfortran               3.0.1                h93005f0_2    defaults
llvm                      4.0.1                hc748206_0    conda-forge
llvm-lto-tapi             4.0.1                h6701bc3_0    conda-forge
mpi                       1.0                     openmpi    conda-forge
openmpi                   3.1.3             h71abe9c_1001    conda-forge
openmpi-mpicc             3.1.3             h79c3c89_1001    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
     active environment : openmpi
    active env location : /Users/mikaelmortensen/anaconda3/envs/openmpi
            shell level : 1
       user config file : /Users/mikaelmortensen/.condarc
 populated config files : /Users/mikaelmortensen/.condarc
          conda version : 4.6.1
    conda-build version : 3.17.7
         python version : 3.6.5.final.0
       base environment : /Users/mikaelmortensen/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/spectralDNS/osx-64
                          https://conda.anaconda.org/spectralDNS/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/mikaelmortensen/anaconda3/pkgs
                          /Users/mikaelmortensen/.conda/pkgs
       envs directories : /Users/mikaelmortensen/anaconda3/envs
                          /Users/mikaelmortensen/.conda/envs
               platform : osx-64
             user-agent : conda/4.6.1 requests/2.18.4 CPython/3.6.5 Darwin/18.2.0 OSX/10.14.2
                UID:GID : 503:20
             netrc file : None
           offline mode : False

```
</details>

**Comment by minrk** [comment]
If you are only building for yourself, you should be able to build with:

    export CONDA_BUILD_SYSROOT=/

but there's more work to do if you are attempting to build redistributable packages. The conda compilers use open source llvm 7, which doesn't yet support Apple's .tbd stub format, adopted in more recent SDKs. To work around this, you need to:

1. download an old mac sdk (10.9 or 10.10, I think)
2. tell the compilers to use this by setting CONDA_BUILD_SYSROOT to point to it

The conda-forge CI setup does this [here](https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/276c13013f674fab262fc3e02bf2e90396334468/recipe/run_conda_forge_build_setup_osx#L12-L23).

**Comment by mikaem** [comment]
Well, it does fix it:-) But it seems like an ugly hack for someone that simply wants to use mpi from conda to work locally?

**Comment by minrk** [comment]
There's an [ongoing discussion](https://github.com/conda-forge/compilers-feedstock/issues/6) about making the conda compilers work by default without any help. Apple makes it surprisingly tricky by changing things on almost every release. The current behavior should indeed work by default once llvm 8 is out with support for TAPI .tbd stubs that Apple started using in their SDKs but didn't open source promptly.

I may look into having openmpi-mpicc set CONDA_BUILD_SYSROOT=/ by default on mac because of this as a possible experiment, since that ought to work better.

**Comment by leofang** [comment]
Close due to inactivity. Feel free to reopen if needed.
