### ISSUE TITLE
Add new mpi provider for mpi-serial

### ISSUE THREAD

**Issue by zklaus** [conda-forge/mpi-feedstock#9]
### Comment:

We, that is me, @xylar, and @mahf708, would like to add mpi-serial as an mpi provider to conda-forge.

This is motivated by problems with newer versions of ESMF that depend on ParallelIO and are no longer working as `nompi`.
[A comment by @billsacks](https://github.com/conda-forge/esmf-feedstock/pull/102#issuecomment-1533871164) points to mpi-serial as a possible solution.

The `mpi-serial` package is pending in conda-forge/staged-recipes#22793, but to integrate it properly into the conda-forge mpi infrastructure, I believe we need to add a new mpi variant here.

- Is this correct?
- Is it ok to add here?
- Must the variant be called the same as the package, i.e. `mpi-serial`, or would `serial` be ok/preferred?

Thanks for your help, @conda-forge/mpi!

**Comment by xylar** [comment]
@ocefpaf, @minrk and @leofang, do you have thoughts on this?

I would suggest `mpi-serial` over just `serial`, though that means the build strings for dependencies would be `mpi_mpi-serial...`, which would be odd.

My group really would benefit from having a solution to this (a working `nompi` version of ESMF sepecifically) by July or so, so it would be really helpful if we can make some headway now.  It seems like the process of adding `mpi-serial` might be fairly involved.

**Comment by leofang** [comment]
I don't have objection here. `mpi-serial` is better as it reflects the package name; `serial` would be causing confusion when this propagates to downstream recipes.

**Comment by mahf708** [comment]
Should we ping core as well?

**Comment by xylar** [comment]
@conda-forge/core, if anyone is interested and has time to engage on this issue, please do.  We would benefit from any advice before we get started adding a new MPI implementation.

**Comment by xylar** [comment]
> I would suggest `mpi-serial` over just `serial`, though that means the build strings for dependencies would be `mpi_mpi-serial...`, which would be odd.

According to https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#build-section:
> The build string cannot contain "-".

So we would need to define this as `mpi_serial` rather than `mpi-serial` and build strings will be `mpi_mpi_serial...`.

**Comment by leofang** [comment]
> @conda-forge/core, if anyone is interested and has time to engage on this issue, please do. We would benefit from any advice before we get started adding a new MPI implementation.

I think @ocefpaf is a core dev and he already gave his thumbs up above 🙂

**Comment by xylar** [comment]
@leofang, thanks, that's a good point.  @ocefpaf, is there anyone else from core you'd want to have a look?  It looks like @isuruf is already taking a look at things so that's very helpful!
